import sys
import pathlib
import pytest
import numpy as np
from httpx import AsyncClient, ASGITransport

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

from app.main import app
from app.model.network import NeuralNetwork
from app.model.layers import Dense
from app.model.loss import CategoricalCrossEntropy
from app.dataset.mnist_loader import load_mnist

# ---------------------------------------------------------------------------
# 1. Numerical Gradient Checking
# ---------------------------------------------------------------------------
def test_numerical_gradient_checking():
    """
    Validate the analytical gradients (backprop) of the actual computation graph
    against numerical finite-difference gradients.
    Since Softmax + CCE is fused, we check the gradient dL/dz at the logits layer.
    """
    np.random.seed(42)
    batch_size = 2
    num_classes = 10
    
    # 1. Create fake logits (z)
    logits = np.random.randn(batch_size, num_classes)
    
    # 2. Create one-hot targets
    y_true = np.zeros((batch_size, num_classes))
    y_true[0, 3] = 1
    y_true[1, 7] = 1
    
    # 3. Analytical Fused Gradient (dL/dz = 1/N * (probs - y_true))
    # Softmax forward
    shifted = logits - np.max(logits, axis=1, keepdims=True)
    exps = np.exp(shifted)
    probs = exps / np.sum(exps, axis=1, keepdims=True)
    
    loss_fn = CategoricalCrossEntropy()
    loss_val = loss_fn.forward(probs, y_true)
    analytical_grad = loss_fn.backward()
    
    # 4. Numerical Gradient using finite differences
    epsilon = 1e-5
    numerical_grad = np.zeros_like(logits)
    
    for i in range(batch_size):
        for j in range(num_classes):
            logits_plus = logits.copy()
            logits_plus[i, j] += epsilon
            
            logits_minus = logits.copy()
            logits_minus[i, j] -= epsilon
            
            # Loss plus
            s_plus = logits_plus - np.max(logits_plus, axis=1, keepdims=True)
            e_plus = np.exp(s_plus)
            p_plus = e_plus / np.sum(e_plus, axis=1, keepdims=True)
            loss_plus = loss_fn.forward(p_plus, y_true)
            
            # Loss minus
            s_minus = logits_minus - np.max(logits_minus, axis=1, keepdims=True)
            e_minus = np.exp(s_minus)
            p_minus = e_minus / np.sum(e_minus, axis=1, keepdims=True)
            loss_minus = loss_fn.forward(p_minus, y_true)
            
            numerical_grad[i, j] = (loss_plus - loss_minus) / (2 * epsilon)
            
    # 5. Compare
    diff = np.abs(analytical_grad - numerical_grad)
    max_diff = np.max(diff)
    
    assert max_diff < 1e-6, f"Gradient check failed! Max diff: {max_diff}"

# ---------------------------------------------------------------------------
# 2. Overfit on small batch
# ---------------------------------------------------------------------------
def test_overfit_small_batch():
    """
    Validate that the model can severely overfit on a small dataset (50 samples).
    """
    X_train, y_train = load_mnist(split='train', subset_size=50)
    
    nn = NeuralNetwork(seed=123)
    
    epochs = 20
    learning_rate = 0.5
    
    initial_loss, initial_acc = nn.evaluate(X_train, y_train)
    
    for _ in range(epochs):
        probs = nn.forward(X_train, training=True)
        y_one_hot = np.zeros((len(y_train), 10))
        y_one_hot[np.arange(len(y_train)), y_train] = 1
        nn.loss_fn.forward(probs, y_one_hot)
        
        d_loss = nn.loss_fn.backward()
        nn.backward(d_loss)
        nn.update_weights(learning_rate)
        
    final_loss, final_acc = nn.evaluate(X_train, y_train)
    
    assert final_loss < initial_loss, f"Loss didn't decrease: {initial_loss} -> {final_loss}"
    assert final_acc > initial_acc, "Accuracy didn't improve"
    assert final_acc == 1.0, f"Expected perfect overfitting (1.0), got {final_acc}"

# ---------------------------------------------------------------------------
# 3. Evaluation on Test Data
# ---------------------------------------------------------------------------
def test_evaluation_test_data():
    """
    Evaluate on test data. Using pre-trained weights to measure real accuracy.
    The goal is simply to substantially exceed random guessing (10%).
    """
    X_test, y_test = load_mnist(split='test', subset_size=100)
    
    # We load the weights generated by our pre-training script
    nn = NeuralNetwork()
    weights_path = pathlib.Path(__file__).parent.parent.parent / "weights" / "model.npz"
    nn.load(weights_path)
    
    loss, accuracy = nn.evaluate(X_test, y_test)
    
    # We do NOT hardcode 90%. We just ensure it's significantly better than random guessing.
    assert accuracy > 0.30, f"Accuracy {accuracy} is too close to random guessing."

# ---------------------------------------------------------------------------
# 4. Save/Load Determinism
# ---------------------------------------------------------------------------
def test_save_load_determinism(tmp_path):
    """
    Ensure loading weights back results in identical predictions.
    """
    X_test, _ = load_mnist(split='test', subset_size=5)
    
    nn1 = NeuralNetwork(seed=42)
    # Forward pass on nn1
    preds1 = nn1.predict(X_test)
    
    # Save nn1
    save_file = tmp_path / "model.npz"
    nn1.save(save_file)
    
    # Load into nn2
    nn2 = NeuralNetwork(seed=999) # different seed
    nn2.load(save_file)
    preds2 = nn2.predict(X_test)
    
    np.testing.assert_array_equal(preds1, preds2)

# ---------------------------------------------------------------------------
# 5. API Tests
# ---------------------------------------------------------------------------
@pytest.mark.asyncio
async def test_api_model_summary():
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as c:
        r = await c.get("/api/v1/model/summary")
    assert r.status_code == 200
    data = r.json()
    assert "architecture" in data
    assert len(data["architecture"]) == 6 # Dense, ReLU, Dense, ReLU, Dense, Softmax

@pytest.mark.asyncio
async def test_api_model_predict():
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as c:
        # 784 zeros
        flat_array = [0.0] * 784
        r = await c.post("/api/v1/model/predict", json={"flat_array": flat_array})
    assert r.status_code == 200
    data = r.json()
    assert "prediction" in data
    assert "probabilities" in data
    assert "intermediate_states" in data
    assert len(data["probabilities"]) == 10

@pytest.mark.asyncio
async def test_api_model_train_start_and_status():
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as c:
        # Start training on a very small subset
        r = await c.post("/api/v1/model/train", json={
            "batch_size": 10,
            "epochs": 1,
            "learning_rate": 0.1,
            "subset_size": 20,
            "validation_split": 0.0
        })
        assert r.status_code == 200
        assert r.json()["message"] == "Training started"
        
        # Check status immediately
        r_status = await c.get("/api/v1/model/status")
        assert r_status.status_code == 200
        assert r_status.json()["status"] in ["training", "completed"]
        
        # Stop training
        r_stop = await c.post("/api/v1/model/stop")
        assert r_stop.status_code == 200

@pytest.mark.asyncio
async def test_get_weights_endpoint():
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        response = await ac.get("/api/v1/model/weights")
        assert response.status_code == 200
        data = response.json()
        assert "layers" in data
        layers = data["layers"]
        assert len(layers) == 3
        assert layers[0]["layer_name"] == "Dense_0"
        assert len(layers[0]["weights"]) == 784
        assert len(layers[0]["weights"][0]) == 128
        assert len(layers[0]["biases"]) == 128
